#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer
{
    float values[];
}
input_data;

layout(set = 0, binding = 1, std430) writeonly buffer OutputBuffer
{
    float16_t values[];
}
output_data;

layout(push_constant) uniform Parameters
{
    uint element_count;
}
parameters;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index < parameters.element_count)
    {
        output_data.values[index] = float16_t(input_data.values[index]);
    }
}
