#version 450
layout(local_size_x = 256) in;
layout(std430, binding = 0) readonly buffer Input { float input_values[]; };
layout(std430, binding = 1) writeonly buffer Output { float output_values[]; };
layout(push_constant) uniform Parameters { uint rows; uint columns; } parameters;
void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index >= parameters.rows * parameters.columns) return;
    uint row = index % parameters.rows;
    uint column = index / parameters.rows;
    output_values[column + row * parameters.columns] = input_values[index];
}
