#version 450

layout(local_size_x = 128) in;

layout(std430, binding = 0) readonly buffer Rhs
{
    float rhs[];
};
layout(std430, binding = 1) readonly buffer Ax
{
    float ax[];
};
layout(std430, binding = 2) writeonly buffer Residual
{
    float residual[];
};

layout(push_constant) uniform Parameters
{
    uint count;
}
parameters;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index < parameters.count)
    {
        residual[index] = rhs[index] - ax[index];
    }
}
