#version 450
layout(local_size_x = 128) in;
layout(std430, binding = 0) buffer Direction { float direction[]; };
layout(std430, binding = 1) readonly buffer Transformed { float transformed[]; };
layout(push_constant) uniform Params { uint count; float beta; } params;
void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index < params.count) direction[index] = transformed[index] + params.beta * direction[index];
}
